### ISSUE TITLE
React-tv router

### ISSUE THREAD

**Issue by Maneeshashokan** [raphamorim/react-tv#126]
Hi, 

Anyone use router for react-tv ? which routing module is there in react-tv

**Comment by raphamorim** [comment]
You can use react-router or other routers to use with React-TV. Should work.

**Comment by raphamorim** [comment]
If you have some issue with that we can open another issue later

**Comment by OliverTr54** [comment]
Does anyone have a working example available?

Thanks in advance,
Oliver
