### ISSUE TITLE
Default focused element

### ISSUE THREAD

**Issue by davidgarsan** [raphamorim/react-tv#129]
Is there a way to set a default focused element as original [Spatial Navigation](https://github.com/luke-chang/js-spatial-navigation#configuration) does with config sections?

**Comment by raphamorim** [comment]
doesn't exists a directly api for it yet. but you can do something like: 
```jsx
const Item = ({focused, setFocus, focusPath}) => {
  focused = (focused) ? 'focused' : 'unfocused'
  setFocus() // set inital setFocus
  return <div onClick={() => { setFocus() }} >It's {focused} Item</div>
}
```

**Comment by davidgarsan** [comment]
Thank you!
But maybe that can be lead to some warnings for updating state in render time (collateral effects).
Anyway, finally I came to this in the Focusable HOC:

`    
componentDidMount() {
    this.addFocusable(findFocusable(this));
    if(this.props.focusPath === this.props.defaultFocus) {
        this.props.setFocus();
    }
}
`
This way I can keep a focusable default element even in complex layouts, at page component level, accesible via react-router too.
