### ISSUE TITLE
How we can test our tv app in real device ? is there any way to install app from usb or is there any simpler way to test ? Like android tv is it possible to install .ipk file ? 

### ISSUE THREAD

**Issue by Maneeshashokan** [raphamorim/react-tv#133]
How we can test our app in real tv device ? is it possible to install .ipk file ?

**Comment by matheusmonte** [comment]
@Maneeshashokan  what is your terget device?

**Comment by raphamorim** [comment]
Hi @Maneeshashokan,
As far as I know, IPK is not compatible with android tv.
react-tv-cli is right now only working for LG WebOS.
Maybe it helps https://medium.com/@raphamorim/developing-for-tvs-with-react-tv-b5b5204964ef

**Comment by Maneeshashokan** [comment]
I don't want to install it into android tv, I need to install it on LG web os tv. Is it possible to install IPK file in LG  WebOS ?

**Comment by dead** [comment]
It is possible, http://webostv.developer.lge.com/develop/app-test/
