### ISSUE TITLE
React TV and react router....

### ISSUE THREAD

**Issue by OliverTr54** [raphamorim/react-tv#140]
Does anyone have a working example of React TV with a react router to a details page?

Thanks in advance,
Oliver

**Comment by OliverTr54** [comment]
Got some example @raphamorim? Thanks a lot!!!

**Comment by OliverTr54** [comment]
Does anybody have an example for this? Please!!!

Thanks, Oliver

**Comment by crippin** [comment]
Hi @OliverTr54 !
I just made a little sample for you, I hope it will help.
https://codesandbox.io/s/03vpz3zx0v

**Comment by raphamorim** [comment]
@crippin that would be nice to have on Readme. If you want to add that :)
