### ISSUE TITLE
React.memo failed

### ISSUE THREAD

**Issue by wyeo** [raphamorim/react-tv#144]
ReactTV.render does not support React.memo utilisation.

I got this error message 

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by matheusmonte** [comment]
@wyeo Can you share some piece of code?

**Comment by wyeo** [comment]
@matheusmonte https://codesandbox.io/s/wovj152n5

**Comment by raphamorim** [comment]
Hmm, I believe the reason of that is that react reconciler is outdated and most of new React features are not supported yet. Created an issue related https://github.com/raphamorim/react-tv/issues/158
