### ISSUE TITLE
Hello, I want to generate ipk  from the react tv project.

### ISSUE THREAD

**Issue by etibar** [raphamorim/react-tv#149]

**Comment by matheusmonte** [comment]
Can you generate a ipk from project's result or source code, Can you explain more?

**Comment by raphamorim** [comment]
Hey @etibar, when you run `react-tv-cli run-webos` it will generate the IPK for you. https://github.com/raphamorim/react-tv/blob/master/packages/react-tv-cli/scripts/webos/run.js#L133

**Comment by raphamorim** [comment]
Unfortunately there’s no `build-webos` to just create the IPK file. Feel free to open a PR if you want to, would be a good feature to have. Closing this issue.
