### ISSUE TITLE
Set correct emulator version

### ISSUE THREAD

**Issue by Aspect26** [raphamorim/react-tv#153]
In https://github.com/raphamorim/react-tv/blob/master/packages/react-tv-cli/scripts/webos/run.js#L107 there is a hardwired version in the output string, it would be better if it was taken from the environment.

Also in https://github.com/raphamorim/react-tv/blob/e2e97a5ee2f8c0e8fc1b008eea3df39f3870dd80/packages/react-tv-cli/scripts/webos/run.js#L9 the version defaults to v3.0.0 if not specified in env. I think it would be better to change it to v5.0.0 since its the current version.

**Comment by raphamorim** [comment]
Closed and fixed by #156
