### ISSUE TITLE
Crash when SDK path contains empty spaces

### ISSUE THREAD

**Issue by Aspect26** [raphamorim/react-tv#154]
This line (and probably some following ones) https://github.com/raphamorim/react-tv/blob/master/packages/react-tv-cli/scripts/webos/run.js#L133 crashes when there is a space in the SDK path.

e.g. my SDK path is `/media/julius/DATA/apps-linux/webOS SDK/webOS_TV_SDK/CLI/bin` and the output from `react-tv-cli run-webos` is 
```
Up Emulator...
 LG WebOS Emulator 3.0.0 succefull running
"LG webOS TV Emulator 5.0.0" {9e8b9f29-44b9-4a6e-3053-2053a70341cb}

Packing...
/bin/sh: 1: /media/julius/DATA/apps-linux/webOS: not found
```

My environment is Ubuntu 20.04;

**Comment by Aspect26** [comment]
Its a little problematic because the default installation folder contains those spaces, so to make it work I have to change it and also all the other environment variables :disappointed:

**Comment by matheusmonte** [comment]
Hey,

I open an PR to solve this issue, but I have a limited access to ubuntu environment. If you are able to test this changes before merge, it will help a lot. 

Thanks
