### ISSUE TITLE
The guys at BBC have done significant work in configuring for diff platforms...

### ISSUE THREAD

**Issue by joshuairl** [raphamorim/react-tv#41]
Hey hey,

LOVE what you're doing here.  Exciting to see work being done in the TV space considering it's so incredibly fragmented.

Wanted to share this, I'm sure you've seen it... but didn't know if you considered using anything from it relating to the vast configuration requirements of the different platforms.

I'm not sure if "build" tools are as important as just flat out having a web app that can hot-load it's configuration based on the current platform since MANY TV platforms just require a URL as the source of the app versus a full build.

But anyway, wasn't sure what your intent was in this regard... https://github.com/bbc/tal

**Comment by raphamorim** [comment]
Thanks for sharing it @joshuairl, I didn't know this project!

The idea of Build tools of React-TV is only to unify/simplify workspace than any other feature.
So yeah, I'm agree with you about it, but is that the reason about Renderer and Builder are distributed packages.
