### ISSUE TITLE
Distribute Packages

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-tv#43]
In a future step, we should distribute every domain package and publish them.

```
- react-tv (Just renderer)
- react-tv-cli (Template and Generators)
- react-tv-simulators (Simulators)
```

**Comment by DChinin** [comment]
@raphamorim what you think about separate packages for platforms and navigation?

**Comment by raphamorim** [comment]
Hm.
I don't have sure about it right now, just because we need to run in multiples platform. Right now I'm only testing it on WebOS, when I start with Orsay, Tizen, PS4.

Then in the near future we will be able to answer that question.

I already think a premature optimization, think on distributed packages based on present unstable renderer hehe

**Comment by raphamorim** [comment]
consider use of Yarn Workspaces.
