### ISSUE TITLE
WebOS1 and WebOS2 - Map constructor does not accept arguments error 

### ISSUE THREAD

**Issue by xorion2** [raphamorim/react-tv#64]
If you get error at Webos1 or Webos2 **Map constructor does not accept arguments** and for the solution;

  **npm install --save babel-polyfill**

and then you can edit it as follows;

```
...................
require("babel-polyfill");
 
const sourcePath = path.join(__dirname, 'src');
 
module.exports = {
  entry: ["babel-polyfill", path.resolve(sourcePath,  'App.js')],
  output: {
    path: __dirname,
    filename: 'bundle.js'
  },
...........................
```

> No need for WebOS 3 +

[](https://babeljs.io/docs/usage/polyfill/)

**Comment by raphamorim** [comment]
Amazing @xorion2 
Thanks for document it! :octocat: <3
