### ISSUE TITLE
Run WebOS Examples

### ISSUE THREAD

**Issue by Lucasktrindade** [raphamorim/react-tv#65]
Installed react-tv globally.
Create proj with init command but when i try to run as it said in documentation. 
Doesn't run as expected, all dependencies are installed.

![image](https://user-images.githubusercontent.com/13908465/33108629-6742c0e0-cf24-11e7-9319-e7755f919a27.png)

**Comment by raphamorim** [comment]
what's the output of `react-tv version`?

**Comment by raphamorim** [comment]
can you show the output of `cat package.json && ls -al` ?

**Comment by Lucasktrindade** [comment]
![image](https://user-images.githubusercontent.com/13908465/33108801-3d6ea422-cf25-11e7-9b01-30d1bdca3915.png)

**Comment by dead** [comment]
Just run `react-tv init` as said in the error and try again 😄 
But I guess react-tv should already initialize it when you create a project.

Just tested here and when using `react-tv init myApp` it doesn't initialize it (create the react-tv folder)

**Comment by raphamorim** [comment]
try it:
`yarn global add react-tv@0.3.0-beta.0` stable version.

an then run `react-tv init` again.

**Comment by raphamorim** [comment]
hehehe yup @dead!

This is bug solved on `0.3.0-beta.0`

**Comment by Lucasktrindade** [comment]
I have to run ```react-tv init ``` inside proj that was generated with ```react-tv  init <my-app> ```

**Comment by raphamorim** [comment]
not now. (if you used `0.3.0-beta.0`)

**Comment by raphamorim** [comment]
you're using `0.3.0-beta.0` just run `run-webos`
