### ISSUE TITLE
Consider use of Samsung/Toast for Builds

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-tv#68]
idea from #66

**Comment by dead** [comment]
I don't think we need Toast for build stuff. It's pretty easy to build packages to Tizen/Orsay/WebOS.
The good thing about Toast is their universal API.
But using stuff like the react-native [platform specific extensions](https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions) make it really easy to implement platform independent components.
Using Toast also would create a huge dependency. And also would make using stuff that are not supported by its API be a pain.

**Comment by raphamorim** [comment]
This argument make sense to me.
I'm closing it until another counter argument.
