### ISSUE TITLE
Failed to up virtualbox emulator

### ISSUE THREAD

**Issue by thiagommedeiros** [raphamorim/react-tv#74]
Hi @raphamorim,

I'm trying to start the LG WebOS Emulator 3.0.0 on Ubuntu 16.04 but I'm getting this error: 

![screenshot from 2017-12-04 21-44-39](https://user-images.githubusercontent.com/19213244/33582499-a73412b8-d93c-11e7-9c86-36a7ae150254.png)

I've already followed the instructions in the react-tv docs to configure the WebOS Environment and the Emulator works fine when I run through the desktop icon.

Do you have any idea how to fix this error?

Thanks!

**Comment by raphamorim** [comment]
Currently WebOS env fails on Linux https://github.com/raphamorim/react-tv/issues/67 😢 
I'm solving it for the next release.

**Comment by raphamorim** [comment]
Just for curiosity: Can you give the absolute path of `LG_webOS_TV_Emulator_RCU`?
It's in your `$webOS_TV_SDK_ENV/../../Emulator`

**Comment by thiagommedeiros** [comment]
All right!

I think that's it: `/usr/local/share/webOS_TV_SDK/Emulator/v3.0.0/`.

![screenshot from 2017-12-04 22-32-35](https://user-images.githubusercontent.com/19213244/33583766-13641216-d943-11e7-9f8f-57abacd23439.png)

**Comment by raphamorim** [comment]
yup, `.app` is for MacOS/OSX only.
I'm trying to know if `LG_webOS_TV_Emulator_linux_x64.jar` is your executable.

**Comment by thiagommedeiros** [comment]
Yes! It's executable. 

I run `java -jar LG_webOS_TV_Emulator_linux_x64.jar -remocon` and the emulator was opened.

**Comment by raphamorim** [comment]
Amazing, give me some minutes and I'll add a fix for it in a release.

**Comment by raphamorim** [comment]
@thiagommedeiros can you retry with `react-tv@0.3.0-beta.2`?

**Comment by raphamorim** [comment]
I just published it. No sure if it gonna work.

**Comment by thiagommedeiros** [comment]
Did not work.

But, instead of `execSync` I changed to `exec` method and it worked and the app runs. This only works when I open WebOS Emulator before execute the `run-webos` command. I think `execSync` don't work because the executable is blocking the command-line.

**Comment by raphamorim** [comment]
Make sense.
Can you send a PR with these changes?

**Comment by thiagommedeiros** [comment]
Sure! I got it!

**Comment by raphamorim** [comment]
Question: using only `exec` works without Emulator opened?

**Comment by thiagommedeiros** [comment]
No, it just opens the remote control. The VirtualBox don't open.

**Comment by raphamorim** [comment]
hmm.. can print the `cat LG_webOS_TV.sh` result?

btw: In a future step we can use fork for child_process(?)

**Comment by raphamorim** [comment]
I guess this scripts can both (virtualbox and jar).

**Comment by thiagommedeiros** [comment]
`LG_webOS_TV_Emulator.sh`
![screenshot from 2017-12-05 01-10-20](https://user-images.githubusercontent.com/19213244/33588311-5b42de12-d959-11e7-8be6-624440d4d0ac.png)


I didn't understand your question.

**Comment by raphamorim** [comment]
Every executable on linux has to be "trackable" @thiagommedeiros.
If you're able to click and open virtualbox and remotecontrol together, we can be able to do the same on CLI. 

We only need to get the path for that script :octocat: 🤔

**Comment by raphamorim** [comment]
can you run this SH? `sh LG_webOS_TV_Emulator.sh`

**Comment by raphamorim** [comment]
Sorry for bothering you te-hehe.
I feel we're close. :P

**Comment by thiagommedeiros** [comment]
hmm.. I got it!

hahaha relax! é nois!!

yeah! `sh LG_webOS_TV_Emulator.sh` it runs the VirtualBox

**Comment by raphamorim** [comment]
lol

**Comment by raphamorim** [comment]
then just need to change by:

```shell
$ sh ./LG_webOS_TV_Emulator.sh && java -jar LG_webOS_TV_Emulator_linux_x64.jar -remocon
```

and should work.

**Comment by thiagommedeiros** [comment]
I'll test it.

**Comment by thiagommedeiros** [comment]
yeeeahh it worked!! :tada: :tada: :tada:

**Comment by raphamorim** [comment]
🥂

**Comment by raphamorim** [comment]
can you send a PR with the changes?
you can debug it using `node <path-to-absolute-cli>`

**Comment by thiagommedeiros** [comment]
yeap :)

I'll send this PR tomorrow! Thank you bro!

**Comment by raphamorim** [comment]
thanks @thiagommedeiros :)
